project:
  title: Bennet Christensen
  type: website
  output-dir: docs
resources:
    - projects/correlated/corr.html
website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
  page-footer:
    left: |
      &copy; Bennet Christensen, 2024<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/)
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a>
editor: visual

